# To have cpu support you need to have this
CPU_FREQ = { value = '*', forced = true }
CPU_FREQ_GOV_PERFORMANCE = '*'
CPU_FREQ_GOV_POWERSAVE = '*'
# For some reason if you select any sort of frequency scaling, intel pstate is forced on
X86_INTEL_PSTATE = { value = '*', forced = true }
X86_AMD_PSTATE = '*'
X86_AMD_PSTATE_UT = '*M'
