BIG_KEYS='*'
KEYS='*'
KEY_DH_OPERATIONS='*'
CRYPTO = { value = '*', forced = '*' }
SYSTEM_TRUSTED_KEYRING='*'
SECONDARY_TRUSTED_KEYRING='*'
SYSTEM_BLACKLIST_KEYRING='*'

[CRYPTO_LIB_CHACHA20POLY1305]
value = '*'
comment = [
  "If not built into the kernel, [BIG_KEYS] won't show up;",
  "building as a module won't work"
]
