EFI='*'
PARTITION_ADVANCED='* '
EFI_PARTITION="*"
SYSFB_SIMPLEFB="*"
DRM="*"
DRM_FBDEV_EMULATION="*"
DRM_SIMPLEDRM="*"
# forced by !EXPERT
FB="*"
FRAMEBUFFER_CONSOLE = { value = "*", forced = true }
VFAT_FS="*M"
EFIVAR_FS="*M"
# forced by ACPI, it's highly unlikely people will disable ACPI...
NLS = { value = "*", forced = true }
NLS_CODEPAGE_437="*M"
NLS_ISO8859_1="*M"
